### ISSUE TITLE
body.toString() in CamelToVertxProcessor

### ISSUE THREAD

**Issue by lburgazzoli** [vert-x3/vertx-camel-bridge#11]
I had a look at CamelToVertxProcessor and it appears that the body of a message is first converted to a type according to the InboundMapping then it is sent/published to vertx using body.toString() : shouldn't it be sent as it is and eventually setting up a MessageCodec ?

https://github.com/vert-x3/vertx-camel-bridge/blob/master/src/main/java/io/vertx/ext/camel/impl/CamelToVertxProcessor.java#L61
https://github.com/vert-x3/vertx-camel-bridge/blob/master/src/main/java/io/vertx/ext/camel/impl/CamelToVertxProcessor.java#L64

**Comment by cescoffier** [comment]
Good question.

If we would use the created type, we may lead to missing codec issues, but I guess this is acceptable as you can add a Camel component in order to transform it to String or Json Object.

**Comment by cescoffier** [comment]
@davsclaus what do you think ?

**Comment by lburgazzoli** [comment]
The main problem here is that body.toString() may be meaningless and most of the time it cannot be translated back to the original object.

**Comment by davsclaus** [comment]
Yes we should avoid the toString style.

So if we can map the Camel body type to a supported codec in vertx then we should try using that approach.

**Comment by cescoffier** [comment]
+1 - gonna fix this right now.
