### ISSUE TITLE
route seems to loose header values for an inOut inbound mapping

### ISSUE THREAD

**Issue by encodeering** [vert-x3/vertx-camel-bridge#21]
Hello,

I just tried to write the response from an inline inOut vertx call back to the disk and noticed, that header values are missing. 

```
// RouteBuilder

override fun configure () {
    from ("stream:in?promptMessage=>")
        .inOut ("direct:code-generator")
            .process ().body { _, headers -> println ("headers: $headers") } // log headers to stdout
                .to ("file://build/code")
}

// Bridge

options.addInboundMapping (InboundMapping.fromCamel ("direct:code-generator").toVertx ("code-generator"))
```

I guess that it could have something to do with the following lines 

```
// CamelToVertxProcessor

if (reply.succeeded()) {
  out.setBody(reply.result().body());
  MultiMapHelper.toMap(reply.result().headers(), in.getHeaders());
} else {
  exchange.setException(reply.cause());
}
```

which uses the _out_ part of an exchange, but changes the headers from the _in_ part - but it's only a guess.

Anything else worked just like a charm, thanks for your work.

**Comment by cescoffier** [comment]
@encodeering You are absolutely right, it's a bug. The cause is the line you found. It should be `out.getHeaders()` instead of `in.getHeaders()`.
