### ISSUE TITLE
Upgrade to newer Camel versions

### ISSUE THREAD

**Issue by davsclaus** [vert-x3/vertx-camel-bridge#50]
What minimum JDK version is VertX 5 based on. As currently we are using old Camel 3.14.x because Java 8 is required.
We may be able to upgrade to newer Camel version if VertX 5 is JDK11 or JDK17 based.

**Comment by vietj** [comment]
that will be JDK 11 for now @davsclaus

**Comment by vietj** [comment]
we are planning to switch the build soonish to JDK 11 , I created this issue for following the effort https://github.com/eclipse-vertx/vert.x/pull/4663

**Comment by vietj** [comment]
Actually we can make an exception for camel bridge I think or think about trying to support multiple versions of camel

**Comment by vietj** [comment]
@davsclaus we can actually proceed to a version bump here since the build properly supports Java 11

**Comment by davsclaus** [comment]
okay upgraded to latest 3.xx that supports java 11.

Camel v4 is Java 17+ and since Camel v3 is EOL by end of this year, is there plans for vertx to jump to java 17 as minimum ?
