### ISSUE TITLE
Temporary map created by MultiMapHelper.toMap

### ISSUE THREAD

**Issue by lburgazzoli** [vert-x3/vertx-camel-bridge#8]
Camel Message's headers in  FromVertxToCamelProducer and CamelToVertxProcessor are set with an helper method MultiMapHelper.toMap which creates a new map for each call:

https://github.com/vert-x3/vertx-camel-bridge/blob/master/src/main/java/io/vertx/ext/camel/impl/MultiMapHelper.java#L40
https://github.com/vert-x3/vertx-camel-bridge/blob/master/src/main/java/io/vertx/ext/camel/impl/FromVertxToCamelProducer.java#L54
https://github.com/vert-x3/vertx-camel-bridge/blob/master/src/main/java/io/vertx/ext/camel/impl/CamelToVertxProcessor.java#L68

This new map is then thrown away as DefaultMessage adds all the values in its own instance of a CaseInsensitiveMap:

https://github.com/apache/camel/blob/master/camel-core/src/main/java/org/apache/camel/impl/DefaultMessage.java#L166

It may be better to create an instance of CaseInsensitiveMap inside of MultiMapHelper.toMap or add an additional parameter to set the destination map, something like:

```java
MultiMapHelper.toMap(vertxMessage.headers(), in.getHeaders());
```

This latest option also ensure that if the message implementation has some default, they will be set.

Make sense? If yes I can send a PR

**Comment by cescoffier** [comment]
Yes it makes sense. A PR would be definitely welcome.

**Comment by lburgazzoli** [comment]
@cescoffier I've rebased the PR against the latest changes

**Comment by lburgazzoli** [comment]
@cescoffier rebased against lates changes, is there anything I need to change to get it merged ?
